Configuration files for action

diff --git a/.github/workflows/wf.yml b/.github/workflows/wf.yml
--- a/.github/workflows/wf.yml
+++ b/.github/workflows/wf.yml
@@ -14,86 +14,85 @@ env:
   AWS_REGION: ap-south-1
   PUBLIC_KEY: ${{ secrets.AWS_PUBLIC_KEY }}
   PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
-
 jobs:
   deploy-infra:
     runs-on: ubuntu-latest
     outputs:
-      SERVER_PUBLIC_IP: ${{ steps.set-ip.outputs.instance_public_ip }}
+      SERVER_PUBLIC_IP: ${{ steps.set-ip.outputs.instance_public_ip}}
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v1
         with:
           terraform_version: 1.7.2
-
       - name: Terraform Init
         run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=ap-south-1"
         working-directory: ./ins-config
-
       - name: Terraform Plan
         run: terraform plan -var="region=ap-south-1" -var="public_key=$PUBLIC_SSH_KEY" -var="access_key=$PUBLIC_KEY" -var="secret_key=$PRIVATE_KEY" -var="private_key=$PRIVATE_SSH_KEY" -var="key_name=deployer-key" -out=PLAN
         working-directory: ./ins-config
-
       - name: Terraform Apply
         run: terraform apply PLAN
         working-directory: ./ins-config
-
       - name: Set output
         id: set-ip
-        run: |
-          INSTANCE_PUBLIC_IP=$(terraform output -raw instance_public_ip)
-          echo "instance_public_ip=${INSTANCE_PUBLIC_IP}" >> $GITHUB_ENV
+        run: echo "instance_public_ip=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
         working-directory: ./ins-config
+deploy-app:
+  runs-on: ubuntu-latest
+  needs: deploy-infra
+  steps:
+    - name: Checkout
+      uses: actions/checkout@v3
 
-  deploy-app:
-    runs-on: ubuntu-latest
-    needs: deploy-infra
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+    - name: Set IP env variable
+      run: echo "SERVER_PUBLIC_IP=${{ needs.deploy-infra.outputs.SERVER_PUBLIC_IP }}" >> $GITHUB_ENV
 
-      - name: Set IP env variable
-        run: echo "SERVER_PUBLIC_IP=${{ needs.deploy-infra.outputs.SERVER_PUBLIC_IP }}" >> $GITHUB_ENV
+    - name: Login to AWS ECR
+      id: login-ecr
+      uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Debug Server Public IP
-        run: echo "SERVER_PUBLIC_IP ${SERVER_PUBLIC_IP}"
+    - name: Deploy Docker images
+      env:
+        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+        REPOSITORY: wf_ltd
+        IMAGE_TAG: ${{ github.sha }}
+        AWS_DEFAULT_REGION: ap-south-1
+      run: |
+        # Build Docker images
+        docker-compose build
 
-      - name: Login to AWS ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
+        # Push Docker images to ECR
+        docker-compose push
 
-      - name: Deploy Docker images
-        env:
-          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          REPOSITORY: wf_ltd
-          IMAGE_TAG: ${{ github.sha }}
-          AWS_DEFAULT_REGION: ap-south-1
-        run: |
-          # Build Docker images
-          docker-compose build
+        # Create private key file and set permissions
+        echo "$PRIVATE_KEY" > private_key
+        chmod 600 private_key
 
-          # Push Docker images to ECR
-          docker-compose push
+        # Extract the hostname from the IP address
+        HOSTNAME=$(ssh-keyscan -H $SERVER_PUBLIC_IP 2>/dev/null | cut -f 2 -d ' ')
+        if [ -z "$HOSTNAME" ]; then
+          echo "Failed to extract hostname. Aborting..."
+          exit 1
+        fi
 
-          # Create private key file and set permissions
-          echo "$PRIVATE_KEY" > private_key
-          chmod 600 private_key
+        # SSH into the server and deploy the Docker containers
+        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$HOSTNAME << 'EOF'
+          sudo apt update
+          sudo apt install docker.io -y
+          sudo apt install docker-compose -y
+          sudo systemctl start docker
+          sudo systemctl enable docker
 
-          # SSH into the server and deploy the Docker containers
-          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$SERVER_PUBLIC_IP << 'EOF'
-            sudo apt update
-            sudo apt install docker.io -y
-            sudo apt install docker-compose -y
-            sudo systemctl start docker
-            sudo systemctl enable docker
+          # Navigate to the directory containing your docker-compose.yaml file
+          cd /path/to/your/docker-compose/directory
 
-            # cd /path/to/your/docker-compose/directory
-            sudo docker-compose pull
-            sudo docker-compose up -d
-          EOF
+          # Pull the latest images and run the Docker Compose app
+          sudo docker-compose pull
+          sudo docker-compose up -d
+        EOF
+
 
   # build-and-push-images:
   #   runs-on: ubuntu-latest
